// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../whosin/Build.js', ['whosin.build'], ['whosin'], {});
goog.addDependency('../../../whosin/WhosIn.js', ['whosin'], [], {});
goog.addDependency('../../../whosin/ui/Renderer.js', ['whosin.ui.Renderer'], ['goog.dom.classlist', 'goog.ui.Component'], {});
